name: FOSSA Snippet Scan

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        
    - name: Install FOSSA CLI
      run: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
        
    - name: Run FOSSA analyze with snippet scanning
      run: |
        fossa analyze --x-snippet-scan
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        
    - name: Run FOSSA test
      run: |
        fossa test
      env:
        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
